export const QUESTIONS = {
  1: "우리 회사를 일하기 좋은 회사로 추천할 의향",
  2: "회사에서 일하는 것이 자랑스럽다",
  3: "주어진 일이 개인적 성취감을 준다",
  4: "앞으로 12개월 이상 더 근무할 의향",
  5: "조직 내에서 내 의견은 존중받는다",
  6: "업무 수행에 필요한 자료 접근 권한",
  7: "내 업무가 회사 목표에 기여하는지 이해",
  8: "기대되는 역할을 명확히 이해",
  9: "역할 수행에 적절한 행동이 무엇인지 이해",
  10: "필요한 스킬을 배울 기회가 있다",
  11: "웰빙 관련 지원을 편하게 요청할 수 있다",
  12: "회사가 웰빙 가이드·프로그램 제공",
  13: "매니저가 성과 향상에 도움되는 피드백 적시 제공",
  14: "매니저가 잘한 일을 인정",
  15: "매니저가 문제 상황 해결을 돕는다",
  16: "매니저와 역량개발·성장을 정기적으로 대화",
  17: "두려움 없이 문제·이슈를 제기할 수 있다",
  18: "차상위 리더가 회사 일을 적시 공유",
  19: "지난 서베이 결과에 조치가 취해졌다",
  20: "회사가 포용적 업무환경 조성에 노력",
  21: "회사에 소속감을 느낀다",
  22: "동료들이 업무를 위해 협업한다",
};

export const QUESTION_BENCHMARKS = {
  1: { medallia: "72%", chubbApac: "54%", fav: "52%" },
  2: { medallia: "73%", chubbApac: "52%", fav: "55%" },
  3: { medallia: "71%", chubbApac: "57%", fav: "57%" },
  4: { medallia: "75%", chubbApac: "75%", fav: "75%" },
  5: { medallia: "67%", chubbApac: "61%", fav: "61%" },
  6: { medallia: "72%", chubbApac: "69%", fav: "69%" },
  7: { medallia: "76%", chubbApac: "73%", fav: "74%" },
  8: { medallia: "79%", chubbApac: "75%", fav: "75%" },
  9: { medallia: "0%", chubbApac: "79%", fav: "79%" },
  10: { medallia: "72%", chubbApac: "55%", fav: "55%" },
  11: { medallia: "0%", chubbApac: "52%", fav: "15%" },
  12: { medallia: "0%", chubbApac: "15%", fav: "37%" },
  13: { medallia: "0%", chubbApac: "37%", fav: "54%" },
  14: { medallia: "72%", chubbApac: "53%", fav: "64%" },
  15: { medallia: "76%", chubbApac: "64%", fav: "64%" },
  16: { medallia: "0%", chubbApac: "64%", fav: "53%" },
  17: { medallia: "66%", chubbApac: "53%", fav: "0%" },
  18: { medallia: "70%", chubbApac: "0%", fav: "0%" },
  19: { medallia: "73%", chubbApac: "0%", fav: "0%" },
  20: { medallia: "0%", chubbApac: "0%", fav: "0%" },
  21: { medallia: "0%", chubbApac: "0%", fav: "0%" },
  22: { medallia: "-", chubbApac: "-", fav: "0%" },
};
